########################
### Workflow Options ###
########################

## List of paired end samples for assembly.
Samples:
  - EXAMPLE1
  - EXAMPLE2

# List of query genes
Queries:
  - EXAMPLE-QUERY

###########################
### Trimmomatic Options ###
###########################

# full name of adapter file
Adapter_file:
  - EXAMPLE-adapters.fa

# Chosen adapter options
Adapter_options:
  - :2:30:10

# Trimmomatic options
Trimmomatic_options:
  - LEADING:5 TRAILING:5 SLIDINGWINDOW:4:15 MINLEN:45

##########################
### BLASTtoGFF Options ###
##########################

Percent_query_coverage:
  - '50'
